### ISSUE TITLE
[REQ] Fix git license

### ISSUE THREAD

**Issue by MarcoRavich** [fikarchamiiiim/PTZ_Controller#2]
Hi there, 1st of all thanks for your (voluntary) work !

In order to push the PTZ controller-software evolution, we're collecting/doxing related projects (yours too) in our [HyMPS project](https://github.com/forart/HyMPS) (under a [dedicated page](https://github.com/forart/HyMPS/blob/main/PTZstuff.md#--)), can you please fix - at least - licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly, as you can see:

![](https://flat.badgen.net/github/license/fikarchamiiiim/PTZ_Controller)
(generator URL: https://flat.badgen.net/github/license/fikarchamiiiim/PTZ_Controller)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse code in their projects which is a determining factor for the success and longevity of any open software.

Last but not least, we've recently opened a discussion about "[near-zero latency multiple (IP) video-streams playing](https://github.com/forart/HyMPS/discussions/17)" - that could be useful for PTZ-control softwares too - to stimulate the confrontation on the topic between developers/maintainers.

Hope that inspires !

**Comment by fikarchamiiiim** [comment]
Hi, thank you for your attention, i have added the LICENCE for this repo.

Hope it will help.

**Comment by MarcoRavich** [comment]
Thanks a lot !

Consider to check [our PTZ-projects page](https://github.com/forart/HyMPS/blob/main/PTZstuff.md#--) where you can find many interesting (re)sources that can help/inspire you to evolve/improve your software.

There's some interesting stuff in the mentioned discussion (_[near-zero latency multiple (IP) video-streams playing](https://github.com/forart/HyMPS/discussions/17)_) too.

Thanks again and hope to see your software grow.
